name: Go Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # Use v1 of golangci-lint as it's more stable with GitHub Actions
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      # Create a v1 compatible configuration
      - name: Create golangci-lint config
        run: |
          cat > .golangci.yml << EOL
          linters:
            disable-all: true
            enable:
              - errcheck
              - govet
              - ineffassign
              - staticcheck
              - unused
              - gocyclo
          linters-settings:
            gocyclo:
              min-complexity: 15
          EOL

      - name: Run golangci-lint
        run: golangci-lint run --out-format=colored-line-number --timeout=5m

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...